CREATE TABLE IF NOT EXISTS `SPRING_SESSION`
(
 `SESSION_ID` char(36) COLLATE utf8_bin NOT NULL,
`CREATION_TIME` bigint(20) NOT NULL,
`LAST_ACCESS_TIME` bigint(20) NOT NULL,
`MAX_INACTIVE_INTERVAL` int(11) NOT NULL,
`EXPIRY_TIME` bigint(20) NOT NULL DEFAULT '0',
`PRINCIPAL_NAME` varchar(100) COLLATE utf8_bin DEFAULT NULL,
PRIMARY KEY (`SESSION_ID`),
KEY `SPRING_SESSION_IX3` (`PRINCIPAL_NAME`)
 )
ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `SPRING_SESSION_ATTRIBUTES`
(
`SESSION_ID` char(36) COLLATE utf8_bin NOT NULL DEFAULT '',
 `ATTRIBUTE_NAME` varchar(200) COLLATE utf8_bin NOT NULL,
  `ATTRIBUTE_BYTES` blob NOT NULL, PRIMARY KEY (‘SESSION_ID‘,‘ATTRIBUTE_NAME‘),
  CONSTRAINT `SPRING_SESSION_ATTRIBUTES_FK`
   FOREIGN KEY (`SESSION_ID`) REFERENCES `SPRING_SESSION` (`SESSION_ID`) ON DELETE CASCADE
   )
   ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin ROW_FORMAT=DYNAMIC;

