package ru.trandefil.spring.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2019-04-01T11:54:50.072+03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://service.spring.com/", name = "ProductService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductService {

    @WebMethod
    @RequestWrapper(localName = "getProduct", targetNamespace = "http://service.spring.com/", className = "GetProduct")
    @ResponseWrapper(localName = "getProductResponse", targetNamespace = "http://service.spring.com/", className = "GetProductResponse")
    @WebResult(name = "return", targetNamespace = "")
    public Product getProduct(
        @WebParam(name = "productId", targetNamespace = "")
        int productId
    );

    @WebMethod
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "http://service.spring.com/", className = "GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "http://service.spring.com/", className = "GetAllProductsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<Product> getAllProducts();
}
